### ISSUE TITLE
Image captions fails - module 'pymdownx.blocks' has no attribute 'makeExtension'

### ISSUE THREAD

**Issue by botkero** [zensical/zensical#47]
### Context

Hi,

Thanks for your great work!

I'm migrating an existing mkdocs project to zensical (just to get a first impression). I noticed a few things (I'm not sure whether I should create an issue for each small things) but at least for this _caption_ feature I thought it would be in your interest.

### Bug description

When I add this line:

```toml
[project.markdown_extensions.pymdownx.blocks.caption]
```

then I get the following error:

```
Error: AttributeError: Failed to initiate extension 'pymdownx.blocks': module 'pymdownx.blocks' has no attribute 'makeExtension'
```

### Related links

- [Report a bug](https://zensical.org/docs/community/contribute/report-a-bug/)
- [Image captions](https://zensical.org/docs/authoring/images/#image-captions)

### Reproduction

[min_reproduction.zip](https://github.com/user-attachments/files/23452826/min_reproduction.zip)

### Steps to reproduce

see bug description

### Browser

Firefox

### Before submitting

- [x] I have read and followed the [bug reporting guidelines](https://zensical.org/docs/community/contribute/report-a-bug/).
- [x] I have attached links to [the documentation](https://zensical.org/docs/), and possibly related [issues](https://github.com/zensical/zensical/issues).
- [x] I assure that I have [removed all customizations](https://zensical.org/docs/community/contribute/report-a-bug/#remove-customizations) before submitting this bug report.
- [x] I have attached a __.zip file__ with a [minimal reproduction](https://zensical.org/docs/community/guides/create-a-reproduction/).

**Comment by facelessuser** [comment]
I am particularly interested in the repsonse to this issue as well.

The old `mkdocs.yml` format perfectly supports all Python Markdown extensions passing allowing for maximum compatibility, even those that are not explicitly stated as supported by Zensical.

I realize that Zensical officially supports a specific set of Python Markdown extensions with the plan of implementing a CommonMark parser and providing a compatibility bridge for these officially supported extensions. I assumed Zensical would still generically serialize input for any Python Markdown extension allowing max compatibility even in the new `toml` format. But now I'm worried that maybe support is more hard-coded in the `toml` format?

Hopefully, this is just an oversight in the `toml` parsing, or that would mean, for maximum Python Markdown compatibility, `mkdocs.yml` **must** be used. That in and of itself is not necessarily a problem, assuming that, for as long as the legacy parser is supported, the all non parser features are equally supported in both the `yml` and `toml` format moving forward.

**Comment by squidfunk** [comment]
Thanks for reporting. We'll look into this issue.

> I realize that Zensical officially supports a specific set of Python Markdown extensions with the plan of implementing a CommonMark parser and providing a compatibility bridge for these officially supported extensions. I assumed Zensical would still generically serialize input for any Python Markdown extension allowing max compatibility even in the new toml format. But now I'm worried that maybe support is more hard-coded in the toml format?

We need to jump through some hoops right now in order to make extension configuration work in YAML and TOML. YAML is a dead-end, since we're intending to completely move to Rust, and this means no PyYAML support.

Right now, for maximum Python compat, you should use `mkdocs.yml`. You should only use `zensical.toml` if you start a new project. Staying on `mkdocs.yml` for the time being ensures that you can build your project with both, MkDocs and Zensical. When we introduce CommonMark, we will move Python Markdown to a separate module, and might just allow configuration via YAML, but this still needs to be worked out.

**Comment by facelessuser** [comment]
@squidfunk This sounds generally reasonable, especially moving the legacy parsing stuff to a separate module with continued support for YAML-based parsing. Is it possible, for convienance, that Zensical look for both `mkdocs.yml` and `zensical.yml` if the former is not found?

**Comment by facelessuser** [comment]
An alternative would be if there was an explicit, generic way to specify a Python function/object binding in `toml` that didn't require explicit hard-coding, users could then freely migrate to `toml` fully without issue. It may be that this is too complicated, though. Captions is not such an extension, though, and I imagine the issue is more with the import path requiring an additional level of import through `blocks`.

**Comment by squidfunk** [comment]
Fixed in 396a282.

@facelessuser a little background why we use special handling for `pymdownx` – the extensions use `.` in their names to qualify names, and we only accounted for two levels. Blocks uses three. In TOML, `.`  has special meaning, which means in order to configure `pymdownx`, you would need to use the following if we wouldn't apply special handling:

``` toml
[project.markdown_extensions."pymdownx.highlight"]
```

Working on compatibility, we deemed this even more error prone than just allowing to omit the quotes, which made it necessary to employ special logic for hoisting the configuration, so you can write:

``` toml
[project.markdown_extensions.pymdownx.highlight]
```

It's not ideal, and definitely a bandaid. The commit above adds an additional level of hoisting for the blocks extension now. We'll see how we handle this in the future once we move out Python Markdown handling of core. In another comment I noted that I could imagine making Python Markdown configurable with YAML, something like `markdown.yml` or so, moving it out of `zensical.toml`, but to allow for easy interop, we decided that we rather go this route for now. We scoped everything under `project` for good reason, so we can easily move things out one by one while providing automatic refactorings in the future, not cluttering the global configuration scope.

Honestly, I wouldn't have expected your interest in Zensical being that big from the start, but we love to have you here!

**Comment by facelessuser** [comment]
@squidfunk I understand. To be honest MkDocs is a dead end right now, and reliable documentation is important to me. So my interest stems from that. Smoothing people's transition between Pymdown Extensions and Zensical works in my favor as well. I realize the future is moving in a different direction, but I know people rely on some of this stuff currently, but also want to switch over. A stable platform where people can maximize what they currently use and can decide how and when to migrate to the the shiny new stuff later I think works in everyone's interest.

**Comment by squidfunk** [comment]
Released as part of [0.0.6](https://github.com/zensical/zensical/releases/tag/0.0.6).

**Comment by botkero** [comment]
Hi,

Maybe I'm missing something, but I still get the same error. I upgraded with `pip install zensical --upgrade` to `0.0.7`.
I also tried a fresh new installation, but...

```
Error: AttributeError: Failed to initiate extension 'pymdownx.blocks': module 'pymdownx.blocks' has no attribute 'makeExtension'
```

@facelessuser maybe you can help me out here? It's me, or?

**Comment by squidfunk** [comment]
@botkero I can confirm. Something's not right yet. Reopening.

**Comment by squidfunk** [comment]
Turns out, I've been stupid. I looked at the branches and cleaned up those that were merged, except for that this one wasn't 🤦‍♂️ Thus https://github.com/zensical/zensical/commit/396a2825d133b61fb438261cef839406f3a3b29a never made the release. I reapplied the fix in https://github.com/zensical/zensical/pull/88/commits/ab69e1ba1cf9617a70f2a7e1b5407f53b4aa1f01 and merged #88, so it'll be definitely included in 0.0.8. Sorry for the inconvenience!

**Comment by squidfunk** [comment]
Released as part of [0.0.8](https://github.com/zensical/zensical/releases/tag/0.0.8)
